version: "v2.23.3-desktop.2"
services:
  backend:
    build: .
    volumes:
      - image_storage:/src/main/resources/storage/dish_photo
      - actual_logs:/logs
    ports:
      - 8081:8081
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - SPRING_DATASOURCE_URL=jdbc:postgresql://PostgreSQL:5432/food_delivery
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    networks:
      - spring-boot-postgres
    depends_on:
      PostgreSQL:
        condition: service_healthy
  PostgreSQL:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=food_delivery
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - spring-boot-postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:
  image_storage:
  actual_logs:
networks:
  spring-boot-postgres:
